spring:
  # yml配置的优先级高于java配置；如果yml配置和java配置同时存在，则yml配置会覆盖java配置
  http-client:
    pool:
      #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
      maxTotalConnect: 1000
      #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
      maxConnectPerRoute: 100
      # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
      connectTimeout: 3000
      # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
      readTimeout: 5000
      # 从连接池获取连接的timeout,不宜过大,ms
      connectionRequestTimout: 200
      # 重试次数
      retryTimes: 3
      charset: UTF-8
      # 长连接保持时间 单位s,不宜过长
      keepAliveTime: 10
      # 针对不同的网址,长连接保持的存活时间,单位s,如果是频繁而持续的请求,可以设置小一点,不建议设置过大,避免大量无用连接占用内存资源
      keepAliveTargetHost:
        www.baidu.com: 5
  data:
    redis:
      host: redis.deqiying.online
      port: 6379
      password: "deqiying"
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
  redisson:
    # 单节点配置
    singleServerConfig:
      # 连接空闲超时，单位：毫秒
      idleConnectionTimeout: 10000
      # 连接超时，单位：毫秒
      connectTimeout: 10000
      # 命令等待超时，单位：毫秒
      timeout: 3000
      # 命令失败重试次数,如果尝试达到 retryAttempts（命令失败重试次数） 仍然不能将命令发送至某个指定的节点时，将抛出错误。
      # 如果尝试在此限制之内发送成功，则开始启用 timeout（命令等待超时） 计时。
      retryAttempts: 3
      # 命令重试发送时间间隔，单位：毫秒
      retryInterval: 1500
      # 密码，没有设置密码时，需要注释掉，否则会报错
      # password: redis.shbeta
      # 单个连接最大订阅数量
      subscriptionsPerConnection: 5
      # 客户端名称
      clientName: "axin"
      # 节点地址
      address: "redis://redis.deqiying.online:6379"
      password: "deqiying"
      # 发布和订阅连接的最小空闲连接数
      subscriptionConnectionMinimumIdleSize: 1
      # 发布和订阅连接池大小
      subscriptionConnectionPoolSize: 50
      # 最小空闲连接数
      connectionMinimumIdleSize: 32
      # 连接池大小
      connectionPoolSize: 64
      # 数据库编号
      database: 1
      # DNS监测时间间隔，单位：毫秒
      dnsMonitoringInterval: 5000
      # 线程池数量,默认值: 当前处理核数量 * 2
      threads: 0
      # Netty线程池数量,默认值: 当前处理核数量 * 2
      nettyThreads: 0
      # 编码
      # 传输模式
      transportMode: "NIO"
      # 配置看门狗的默认超时时间为30s，这里改为 10s
      lockWatchdogTimeout: 10000
