spring:
  # yml????????java?????yml???java????????yml?????java??
  http-client:
    pool:
      #??????????0????????0??????????????????
      maxTotalConnect: 1000
      #??????????,?????????,????????????
      maxConnectPerRoute: 200
      # ?????????????????,ms , ???21?,????tcp????????????,??tcp?????20?
      connectTimeout: 3000
      # ????????????????????,???????,???socket timeout,ms
      readTimeout: 5000
      # ?????????timeout,????,ms
      connectionRequestTimout: 200
      # ????
      retryTimes: 3
      charset: UTF-8
      # ??????? ??s,????
      keepAliveTime: 10
      # ???????,??????????,??s,???????????,???????,???????,??????????????
      keepAliveTargetHost:
        www.baidu.com: 5